print("---------------------------------------------")
print("Tugas 1 Sisop Kelas B")
print("---------------------------------------------")
print("Nama : Lisya Septyo Ningrum")
print("NPM : 21083010003")
print("---------------------------------------------")
print("Notes :")
print("Hallo dunia!!!!")
print("Ini adalah skrip bash pertamaku di Linux")
